version: "3"
services:
  web:
    image: nodeimagews
    container_name: web-scraping-mvp
    restart: always
    build: .
    ports:
    - "4000:4000"
    volumes:
    - .:/usr/src/app
    environment:
      - HOST=0.0.0.0
      - PORT=4000